# username/repository
id: majid-akbari/JQuery-expression-builder
# name of the software
name: JQuery ExpressionBuilder
# current version of the software
version: 2.1
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon: ico

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
download:
  popup: false
  url: https://github.com/majid-akbari/JQuery-expression-builder/archive/v2.1.zip

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/majid-akbari/JQuery-expression-builder

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/majid-akbari/JQuery-expression-builder
  - title: Issues
    url: https://github.com/majid-akbari/JQuery-expression-builder/issues

# header
header:
  color1: "#4a9ab5"
  color2: "#0e3f50"
  trianglify: true

# google analytics
analytics:
  account: UA-121479203-1
  domain: exp.js.org

# github buttons
githubButton:
  user: majid-akbari
  repo: JQuery-expression-builder

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
